export type WatermarkPositionType =
  | "leftTop"
  | "leftBottom"
  | "leftCenter"
  | "rightTop"
  | "rightCenter"
  | "rightBottom"
  | "center"
  | "topCenter"
  | "bottomCenter";

export type WatermarkTextFont =
  | "Arial"
  | "Andalé Mono"
  | "Baskerville"
  | "Bradley Hand"
  | "Brush Script MT"
  | "Comic Sans MS"
  | "Courier"
  | "Georgia"
  | "Helvetica"
  | "Lucida"
  | "Luminari"
  | "Monaco"
  | "Palatino"
  | "Verdana"
  | "Sofia"
  | "Tahoma"
  | "Trebuchet MS"
  | "Times New Roman";
